#!/bin/bash

[ -z $1 ] && I='all' || I=$1

sudo wg show $1 | grep -P 'latest|ips' | awk '
BEGIN{buff="123"}
{
    fl=0;
    if($1=="allowed") buff=$3;
    if($1=="latest"){
        fl=1;
        buff=buff" \t"$3" "$4" "$5" "$6" "$7" "$8" "$9" "$10" "$11
    }
    if(fl==1){
        print buff;
        buff="";
    }
}' | sed "s/\/32//1" > /var/tmp/wgdump-$I
